# Generated by Django 5.2.1 on 2025-06-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField()),
                ('envio_id', models.IntegerField()),
                ('fuente', models.CharField(default='Hyvolution', max_length=100)),
            ],
            options={
                'unique_together': {('envio_id', 'fuente')},
            },
        ),
    ]
