# Generated by Django 5.2.1 on 2025-07-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_feria_actualizacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actualizacion',
        ),
        migrations.DeleteModel(
            name='Feria',
        ),
    ]
