"""
Django settings for centralizador_leads project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'ferias'
LOGOUT_REDIRECT_URL = 'login'




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gj*r(94h0n)lvb2yku9=hbi4l@cblh5i#p1^=e)s%)%wqe_0r*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'leads',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'centralizador_leads.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'centralizador_leads.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


HYVOLUTION_API_TOKEN = "D.O#40TvIS-F*c_Px;Ij61V/e6a"
SEGURIDAD_API_TOKEN = "Y211eooJEdxWZzP6pcMGIGm7jgCNNYs6Jmlv4T9kH7mAJlW3c0gsUDGjTB6wvWW1VprSTiOxFBXdToM4kYvrrGEWh37kmKbrU0y6qMq1hyRPDwAqORXu0lj7BLqm0QQH"
EXPONAVAL_API_TOKEN = "E84UCLavPJZqXrql9aBKrktmr9VnNbRNFQS0dHKk1l4ukO4sy81OFveQ6rfvbmR8AR2ZZWMnFXXHFWujQ6ZwMtYsPGbkI1o5a5nhQ9Rg8PufaYVws8Qw48gt4cmwlQ9F"
TRANSPORT_API_TOKEN = "2ss12kei8j597TXrBV7csQ3JLuv4b6e40pBsM7DHdtcAi5MnwM"
ENLOCE_API_TOKEN = "saum77blZZ7AfmLQ94sWMkO5b8qnW4AoICCnbpmoVxV5N2na66"
EXPOSALUD_API_TOKEN = "UhPD82ty6lWBiToYy8D5gu7PFCN4JqA15SeLsi53dEQG1alVoJa"
EXPOVIVIENDA_API_TOKEN = "nAVnbAZM0bC3swCIjC7YSJN72v8wR1woPgedySrV1bAEz99nds"
AQUASUR_API_TOKEN = "DuM8z8WdkT837R808tsXkJ0TUrdaUGyUzqAMfee6dekOrKr1un"
AQUASURTECH_API_TOKEN = "k9ss5kNdhjI02b6n2iIq9Bir2dcuZRGsThR1bAGRCfT6noxNAH"
EXPOMIN_API_TOKEN = "7xjqquxHWpmjoarfNtvcNeb5p2k7gJj0SKbqutuD1qu1JpsuS5"
